yarnPath: .yarn/releases/yarn-4.0.1.cjs
compressionLevel: 9
logFilters:
  # suppress "package not found in cache" log - https://yarnpkg.com/advanced/error-codes#yn0013---fetch_not_cached
  - code: YN0013
    level: discard

nodeLinker: node-modules
